import { HardwareSpec, ThemeConfig } from '@/types/setup';

export const THEMES: Record<'neon-noir' | 'gamer-rgb', ThemeConfig> = {
  'neon-noir': {
    mode: 'neon-noir',
    name: 'Neon Night',
    bgGradStart: '#080205',
    bgGradEnd: '#14030a',
    wireframeEmissive: '#ff0033',
    emissiveIntensity: 2.2,
    accentColor: '#ff0033',
    secondaryAccent: '#88001b',
    panelBg: 'rgba(15, 3, 8, 0.85)',
  },
  'gamer-rgb': {
    mode: 'gamer-rgb',
    name: 'ROYGBIV',
    bgGradStart: '#040914',
    bgGradEnd: '#091326',
    wireframeEmissive: '#00f0ff',
    emissiveIntensity: 2.8,
    accentColor: '#00f0ff',
    secondaryAccent: '#ff00aa',
    panelBg: 'rgba(4, 15, 30, 0.85)',
  },
};

export const HARDWARE_SPECS: Record<string, HardwareSpec> = {
  overview: {
    id: 'overview',
    name: 'Full Desk Workstation',
    category: 'creator',
    subtitle: 'Custom Stream & Gaming Rig',
    specs: [
      { label: 'OS', value: 'Windows 11 Home 64-bit' },
      { label: 'Display', value: 'AOC Gaming CU34G2XP/BK 34" Ultrawide 1440p @ 100Hz' },
      { label: 'Platform', value: 'AMD AM4 Socket / ROG Strix B550-F' },
      { label: 'Audio & Mic', value: 'Fifine AM8 Mic, SC3 Mixer, Fosi K5 DAC' },
      { label: 'Headsets', value: 'OneOdio Monitor 80, Retro Over-Ears, OneOdio A70' },
      { label: 'Peripherals', value: 'Logitech G413 TKL SE, G502 HERO, Perixx PERIPAD-303, AKAI LPD8' },
    ],
    description: 'A stylized cybernetic desk setup featuring tailored custom audio accessories, dedicated numpad, stream deck pads, and high-airflow PC enclosure.',
    position: [0, 0, 0],
    cameraTarget: [0, 0.3, 0],
    cameraPosition: [0, 2.0, 4.2],
  },
  cpu: {
    id: 'cpu',
    name: 'AMD Ryzen 5 5600',
    category: 'pc',
    subtitle: 'Processor (CPU)',
    specs: [
      { label: 'Cores / Threads', value: '6 Cores / 12 Threads' },
      { label: 'Architecture', value: 'Vermeer 7nm Technology' },
      { label: 'Base / Boost Clock', value: '3.5 GHz / 4.4 GHz' },
      { label: 'Cache', value: '32MB L3 Cache' },
    ],
    description: 'High-efficiency 6-core processor delivering crisp 1440p gaming and real-time audio stream encoding.',
    position: [1.9, 1.05, -0.1],
    cameraTarget: [1.9, 1.05, -0.1],
    cameraPosition: [0.8, 1.15, 0.9],
  },
  gpu: {
    id: 'gpu',
    name: 'ASUS AMD Radeon RX 7600',
    category: 'pc',
    subtitle: 'Graphics Card (GPU)',
    specs: [
      { label: 'VRAM', value: '8176 MB GDDR6' },
      { label: 'Vendor', value: 'ASUSTeK Computer Inc' },
      { label: 'Architecture', value: 'RDNA 3 (6nm)' },
      { label: 'Ray Accelerators', value: '32 Dedicated Units' },
      { label: 'Output Resolution', value: '3440 x 1440 @ 100Hz' },
    ],
    description: 'RDNA3 powered graphics card driving high-fps Ultrawide gaming and hardware-accelerated video rendering.',
    position: [1.8, 0.55, 0.0],
    cameraTarget: [1.8, 0.55, 0.0],
    cameraPosition: [0.7, 0.65, 1.0],
  },
  ram: {
    id: 'ram',
    name: '32.0GB Dual-Channel DDR4',
    category: 'pc',
    subtitle: 'System Memory',
    specs: [
      { label: 'Capacity', value: '32GB (2x16GB)' },
      { label: 'Type / Speed', value: 'DDR4 @ 1054MHz (2108MHz Effective)' },
      { label: 'Timings', value: 'CL16-18-18-35' },
      { label: 'Channel Mode', value: 'Dual-Channel Active' },
    ],
    description: 'High-speed dual-channel memory modules providing seamless multitasking between high-bitrate streaming software and heavy games.',
    position: [1.9, 1.05, 0.2],
    cameraTarget: [1.9, 1.05, 0.2],
    cameraPosition: [0.8, 1.15, 1.0],
  },
  mobo: {
    id: 'mobo',
    name: 'ASUS ROG STRIX B550-F GAMING',
    category: 'pc',
    subtitle: 'Motherboard',
    specs: [
      { label: 'Socket', value: 'AM4' },
      { label: 'Chipset', value: 'AMD B550' },
      { label: 'Form Factor', value: 'ATX' },
      { label: 'Audio Engine', value: 'SupremeFX S1220A Codec' },
    ],
    description: 'Gaming motherboard featuring PCIe 4.0 expansion, robust power delivery, and glowing ROG Cybertext aura aesthetics.',
    position: [1.9, 0.75, -0.1],
    cameraTarget: [1.9, 0.75, -0.1],
    cameraPosition: [0.6, 0.95, 1.2],
  },
  storage: {
    id: 'storage',
    name: 'Dual SSD Array (1.23 TB Total)',
    category: 'pc',
    subtitle: 'Storage Drive Bay',
    specs: [
      { label: 'Primary SSD', value: '931GB Samsung SSD 870 QVO 1TB' },
      { label: 'Secondary SSD', value: '223GB PNY CS900 240GB SSD' },
      { label: 'Interface', value: 'SATA III 6Gb/s' },
      { label: 'Health Status', value: 'Good / 100%' },
    ],
    description: 'Fast solid-state storage configuration storing the operating system, games library, and stream media recordings.',
    position: [1.9, 0.25, 0.3],
    cameraTarget: [1.9, 0.25, 0.3],
    cameraPosition: [0.8, 0.35, 1.0],
  },
  monitor: {
    id: 'monitor',
    name: 'AOC Gaming CU34G2XP/BK Ultrawide',
    category: 'monitors',
    subtitle: '34" Curved Monitor',
    specs: [
      { label: 'Native Resolution', value: '3440 x 1440 (21:9 WQHD)' },
      { label: 'Refresh Rate', value: '100 Hz' },
      { label: 'Panel Type', value: 'Curved VA Panel (1500R)' },
      { label: 'Color Space', value: 'SRGB 120% / HDR Ready' },
    ],
    description: 'Immersive ultrawide curved monitor providing expansive screen real estate for immersive gaming and side-by-side editing windows.',
    position: [-0.2, 0.7, -0.45],
    cameraTarget: [-0.2, 0.7, -0.45],
    cameraPosition: [-0.2, 0.7, 1.8],
  },
  'audio-station': {
    id: 'audio-station',
    name: 'Fifine AmpliGame AM8 & SC3 Mixer',
    category: 'audio',
    subtitle: 'Broadcast Studio Mic & Interface',
    specs: [
      { label: 'Microphone', value: 'Fifine AmpliGame AM8 (XLR / USB Dynamic)' },
      { label: 'Audio Mixer', value: 'Fifine AmpliGame SC3 (4-Channel Interface)' },
      { label: 'DAC / Amp', value: 'Fosi Audio K5 Gaming DAC' },
      { label: 'Controls', value: 'Tactile Faders, Gain Knobs, RGB Accents' },
    ],
    description: 'Complete broadcast audio suite with the Fifine AmpliGame AM8 dynamic studio mic paired with the Fifine SC3 audio interface and Fosi K5 DAC.',
    position: [-1.5, 0.2, 0.25],
    cameraTarget: [-1.5, 0.2, 0.25],
    cameraPosition: [-1.5, 0.6, 1.2],
  },
  headphones: {
    id: 'headphones',
    name: 'Triple Headphone Station',
    category: 'audio',
    subtitle: '3x Audiophile & Studio Headsets',
    specs: [
      { label: 'Headset #1', value: 'OneOdio Monitor 80 (Open-Back Studio)' },
      { label: 'Headset #2', value: 'Retro Over-Ears (Classic Vintage)' },
      { label: 'Headset #3', value: 'OneOdio A70 (Dual-Duty Wireless / Wired)' },
      { label: 'Stand', value: 'Triple Heavyweight Hanger Tree' },
    ],
    description: 'Custom triple headphone stand housing the open-back OneOdio Monitor 80, vintage Retro Over-Ears, and versatile OneOdio A70 dual-duty headsets.',
    position: [-2.0, 0.35, -0.2],
    cameraTarget: [-2.0, 0.35, -0.2],
    cameraPosition: [-2.0, 0.5, 0.8],
  },
  'akai-lpd8': {
    id: 'akai-lpd8',
    name: 'AKAI LPD8 Controller',
    category: 'creator',
    subtitle: 'Stream Deck & MIDI Trigger Pad',
    specs: [
      { label: 'Pad Count', value: '8 Velocity-Sensitive RGB Pads' },
      { label: 'Knobs', value: '8 Q-Link Assignable Rotary Controls' },
      { label: 'Function', value: 'OBS Scene Switcher & Macro Deck' },
      { label: 'Connectivity', value: 'USB-C Bus Powered' },
    ],
    description: 'Compact AKAI LPD8 MIDI controller mapped as a physical stream deck for switching scenes, toggling mutes, and triggering soundboards.',
    position: [-0.9, -0.03, 0.45],
    cameraTarget: [-0.9, -0.03, 0.45],
    cameraPosition: [-0.9, 0.5, 1.05],
  },
  numpad: {
    id: 'numpad',
    name: 'Perixx PERIPAD-303',
    category: 'peripherals',
    subtitle: 'Separate Numeric Keyboard',
    specs: [
      { label: 'Model', value: 'Perixx PERIPAD-303' },
      { label: 'Switch Type', value: 'Tactile Mechanical Switches' },
      { label: 'Keycaps', value: 'Double-shot PBT Keycaps' },
      { label: 'Layout', value: '21-Key Extended Numpad' },
      { label: 'Lighting', value: 'Per-Key Emissive Backlight' },
    ],
    description: 'Dedicated standalone mechanical numpad placed beside the main keyboard for efficient numeric input and custom shortcut macros.',
    position: [0.7, -0.03, 0.45],
    cameraTarget: [0.7, -0.03, 0.45],
    cameraPosition: [0.7, 0.5, 1.05],
  },
  keyboard: {
    id: 'keyboard',
    name: 'Logitech G G413 TKL SE',
    category: 'peripherals',
    subtitle: 'Tactile Mechanical Gaming Keyboard',
    specs: [
      { label: 'Switch Type', value: 'Tactile Mechanical Switches' },
      { label: 'Keycaps', value: 'PBT Keycaps' },
      { label: 'Top Case', value: 'Black Brushed Aluminum Top Case' },
      { label: 'Lighting', value: 'White LED Backlighting' },
      { label: 'Rollover', value: '6-Key Rollover with Anti-Ghosting' },
    ],
    description: 'Minimalist TKL mechanical gaming keyboard featuring tactile mechanical switches, PBT keycaps, and durable brushed aluminum top case.',
    position: [-0.2, -0.03, 0.45],
    cameraTarget: [-0.2, -0.03, 0.45],
    cameraPosition: [-0.2, 0.55, 1.15],
  },
  mouse: {
    id: 'mouse',
    name: 'Logitech G502 HERO',
    category: 'peripherals',
    subtitle: 'High Performance Gaming Mouse',
    specs: [
      { label: 'Sensor', value: 'HERO 25K Optical Sensor (25,600 DPI)' },
      { label: 'Buttons', value: '11 Programmable Buttons' },
      { label: 'Weights', value: '5x 3.6g Removable Weights' },
      { label: 'Wheel', value: 'Dual-mode Hyper-Fast Scroll Wheel' },
      { label: 'Lighting', value: 'LIGHTSYNC RGB' },
    ],
    description: 'Iconic gaming mouse equipped with the advanced HERO 25K optical sensor, customizable weights, and hyper-fast scroll wheel.',
    position: [0.4, -0.03, 0.45],
    cameraTarget: [0.4, -0.03, 0.45],
    cameraPosition: [0.4, 0.5, 1.05],
  },
};
