import { WallpaperItem } from './types';

export const WALLPAPERS_DATA: WallpaperItem[] = [
  {
    id: 'wallpaper-willow-core',
    title: 'Willow Particle Core',
    type: 'html',
    description: 'Dynamic kinetic typography particle engine featuring explosive bass shockwaves, floaty orbit physics, and mouse repulsion.',
    steamWorkshopUrl: 'https://steamcommunity.com/id/zfw1ll0w/myworkshopfiles/',
    resolution: '4K Ultra HD (3840×2160)',
    aspectRatio: '16:9',
    src: '/wallpapers/wallpaper-willow/index.html',
    posterUrl: '/images/zedf-banner.jpg',
    tags: ['Interactive', 'Audio Reactive', 'Particles', 'HTML5', '60 FPS'],
    features: ['Bass Shockwaves', 'Kinetic Typography', 'Mouse Repulsion', 'Live Aura Glow'],
    accentColor: '#06b6d4',
    author: 'w1ll0w',
  },
  {
    id: 'cyber-horizon-live',
    title: 'Cyber Horizon HUD',
    type: 'html',
    description: 'Real-time interactive cyber grid with live digital clock, cursor shockwaves, and ambient particle physics.',
    steamWorkshopUrl: 'https://steamcommunity.com/id/zfw1ll0w/myworkshopfiles/',
    resolution: '4K Ultra HD (3840×2160)',
    aspectRatio: '16:9',
    src: '/wallpapers/interactive-demo/index.html',
    posterUrl: '/images/zedf-banner.jpg',
    tags: ['Interactive', 'Cyberpunk', 'Clock HUD', 'HTML5'],
    features: ['Interactive Particles', 'Live Real-time Clock', 'Mouse Shockwaves'],
    accentColor: '#38bdf8',
    author: 'w1ll0w',
  },
  {
    id: 'neon-city-rain',
    title: 'Midnight Rain in Neo-Tokyo',
    type: 'video',
    description: 'Atmospheric rainy street in Neo-Tokyo with dynamic puddle reflections, volumetric neon glow, and soft lo-fi audio.',
    steamWorkshopUrl: 'https://steamcommunity.com/id/zfw1ll0w/myworkshopfiles/',
    resolution: 'Ultrawide (3440×1440)',
    aspectRatio: '21:9',
    src: '/wallpapers/wallpaper-willow/index.html',
    posterUrl: '/images/zedf-banner.jpg',
    tags: ['Scene', 'Ultrawide', 'Rain Effects', 'Lo-Fi', 'Atmospheric'],
    features: ['Smooth 60fps Loop', 'Puddle Reflections', 'Subtle Audio'],
    accentColor: '#38bdf8',
    author: 'w1ll0w',
  },
  {
    id: 'deep-space-nebula',
    title: 'Nebula Genesis [Audio Responsive]',
    type: 'html',
    description: 'Deep cosmic nebula with celestial starbursts and responsive orbital dynamics.',
    steamWorkshopUrl: 'https://steamcommunity.com/id/zfw1ll0w/myworkshopfiles/',
    resolution: '4K Ultra HD (3840×2160)',
    aspectRatio: '16:9',
    src: '/wallpapers/interactive-demo/index.html',
    posterUrl: '/images/zedf-banner.jpg',
    tags: ['Cosmic', 'Audio Reactive', 'Space', 'Particles'],
    features: ['Dynamic Lighting', 'Interactive Mouse Parallax', 'Clean Minimalist'],
    accentColor: '#a855f7',
    author: 'w1ll0w',
  },
  {
    id: 'retro-synth-drift',
    title: 'Synthwave Highway 1984',
    type: 'video',
    description: 'Retro 80s outrun endless sunset drive through neon palm wireframes with subtle VHS scanlines.',
    steamWorkshopUrl: 'https://steamcommunity.com/id/zfw1ll0w/myworkshopfiles/',
    resolution: '1440p (2560×1440)',
    aspectRatio: '16:9',
    src: '/wallpapers/interactive-demo/index.html',
    posterUrl: '/images/zedf-banner.jpg',
    tags: ['Retro', 'Synthwave', 'Looping', 'Vaporwave'],
    features: ['Seamless Loop', 'VHS Grain Toggle', 'Vibrant Gradients'],
    accentColor: '#f43f5e',
    author: 'w1ll0w',
  },
  {
    id: 'zen-sakura-shrine',
    title: 'Sakura Petals at Moonlight',
    type: 'scene',
    description: 'Peaceful Japanese shrine with wind-blown falling sakura petals, soft lanterns, and water ripples.',
    steamWorkshopUrl: 'https://steamcommunity.com/id/zfw1ll0w/myworkshopfiles/',
    resolution: '4K Ultra HD (3840×2160)',
    aspectRatio: '16:9',
    src: '/wallpapers/interactive-demo/index.html',
    posterUrl: '/images/zedf-banner.jpg',
    tags: ['Nature', 'Anime', 'Peaceful', 'Sakura'],
    features: ['Wind Physics', 'Lantern Glow', 'Ambient Ripples'],
    accentColor: '#ec4899',
    author: 'w1ll0w',
  },
];
